### ISSUE TITLE
`authorized_keys` should properly handle array values

### ISSUE THREAD

**Issue by coreyti** [pivotal-cf-experimental/remote-pairing-release#15]
Given the following manifest snippet,

```yaml
  properties:
    sshd:
      authorized_keys:
      - ssh-rsa <redacted> host@tunnel
      - ssh-rsa <redacted> host@tunnel
```

SSH tunnel session hosts should be able to successfully authenticate. That is, the `authorized_keys` file on the SSH tunnel server should be rendered correctly.

Current:

```
["<redacted>", "<redacted>"]
```

Desired:

```
<redacted> host@tunnel
<redacted> host@tunnel
```
